on:
  issue_comment:
    types: [created]
  issues:
    types: [opened, edited]

jobs:
  claude-response:
    if: contains(github.event.comment.body, '@claude') || contains(github.event.issue.body, '@claude')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Claude Code Action
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_instructions: |
            あなたは専属プロジェクトマネジメントアシスタントです。
            スマホからの簡潔な指示に対して適切で実用的な回答を提供してください。

            ## コンテキスト制御ルール
            
            ### デフォルト動作（本業優先）
            - 通常の質問はproject-management-systemディレクトリを主体として回答
            - N.Avenueの本業プロジェクト（OIP、AW3A、N.Avenue Club、投資案件等）を参照
            
            ### 副業モード（キーワード検出時）
            以下のキーワードが質問に含まれる場合、side-businessディレクトリを主体として回答：
            - "副業"
            - "D inc"、"D株式会社"  
            - "富士フイルム"
            - "GCT"、"後藤さん"
            - "side-business"
            
            ### 回答時の指針
            - 情報源を明示する（どのディレクトリから情報を取得したか）
            - 副業キーワードがない限り、本業優先で回答
            - CLAUDE.mdファイルの設定に従ってコンテキストを制御
